from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Department', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('name_ar', models.CharField(max_length=100)),
            ('name_en', models.CharField(max_length=100)),
            ('cost_center', models.CharField(blank=True, max_length=20)),
        ]),
        migrations.CreateModel(name='Employee', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('employee_number', models.CharField(max_length=20, unique=True)),
            ('name_ar', models.CharField(max_length=255)),
            ('name_en', models.CharField(max_length=255)),
            ('national_id', models.CharField(blank=True, max_length=20)),
            ('iqama_number', models.CharField(blank=True, max_length=20)),
            ('passport_number', models.CharField(blank=True, max_length=30)),
            ('gosi_number', models.CharField(blank=True, max_length=20)),
            ('nationality', models.CharField(choices=[('saudi','Saudi'),('expat','Expat')], max_length=10)),
            ('job_title_ar', models.CharField(max_length=200)),
            ('job_title_en', models.CharField(blank=True, max_length=200)),
            ('hire_date', models.DateField()),
            ('termination_date', models.DateField(blank=True, null=True)),
            ('status', models.CharField(choices=[('active','Active'),('terminated','Terminated'),('on_leave','On Leave')], default='active', max_length=15)),
            ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('bank_name', models.CharField(blank=True, max_length=100)),
            ('bank_code', models.CharField(blank=True, max_length=20)),
            ('iban', models.CharField(blank=True, max_length=34)),
            ('contract_type', models.CharField(default='permanent', max_length=20)),
            ('contract_start', models.DateField(blank=True, null=True)),
            ('contract_end', models.DateField(blank=True, null=True)),
            ('probation_end', models.DateField(blank=True, null=True)),
            ('annual_leave_balance', models.DecimalField(decimal_places=1, default=Decimal('21.0'), max_digits=5)),
            ('sick_leave_balance', models.DecimalField(decimal_places=1, default=Decimal('30.0'), max_digits=5)),
            ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
            ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ]),
        migrations.AddField(model_name='department', name='manager', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee')),
        migrations.CreateModel(name='LeaveType', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('name_ar', models.CharField(max_length=100)),
            ('name_en', models.CharField(max_length=100)),
            ('code', models.CharField(max_length=20, unique=True)),
            ('default_days', models.PositiveIntegerField(default=0)),
            ('is_paid', models.BooleanField(default=True)),
        ]),
        migrations.CreateModel(name='LeaveRequest', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('start_date', models.DateField()),
            ('end_date', models.DateField()),
            ('days', models.DecimalField(decimal_places=1, max_digits=5)),
            ('reason', models.TextField(blank=True)),
            ('status', models.CharField(choices=[('pending','Pending'),('approved','Approved'),('rejected','Rejected'),('cancelled','Cancelled')], default='pending', max_length=15)),
            ('rejection_reason', models.TextField(blank=True)),
            ('approved_at', models.DateTimeField(blank=True, null=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype')),
            ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='Attendance', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('date', models.DateField()),
            ('check_in', models.TimeField(blank=True, null=True)),
            ('check_out', models.TimeField(blank=True, null=True)),
            ('status', models.CharField(default='present', max_length=15)),
            ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ('notes', models.TextField(blank=True)),
            ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
        ], options={'unique_together': {('employee', 'date')}}),
        migrations.CreateModel(name='PayrollRun', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('period_month', models.PositiveSmallIntegerField()),
            ('period_year', models.PositiveIntegerField()),
            ('status', models.CharField(choices=[('draft','Draft'),('calculated','Calculated'),('approved','Approved'),('paid','Paid')], default='draft', max_length=15)),
            ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ('total_gosi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ('total_gosi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ('employee_count', models.PositiveIntegerField(default=0)),
            ('wps_submitted', models.BooleanField(default=False)),
            ('wps_submitted_at', models.DateTimeField(blank=True, null=True)),
            ('wps_reference', models.CharField(blank=True, max_length=100)),
            ('wps_file_generated', models.BooleanField(default=False)),
            ('paid_at', models.DateTimeField(blank=True, null=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
            ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to=settings.AUTH_USER_MODEL)),
        ], options={'unique_together': {('period_month', 'period_year')}}),
        migrations.CreateModel(name='PayrollLine', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ('gosi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('gosi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ('bank_name', models.CharField(blank=True, max_length=100)),
            ('iban', models.CharField(blank=True, max_length=34)),
            ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee')),
            ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.payrollrun')),
        ], options={'unique_together': {('payroll', 'employee')}}),
        migrations.CreateModel(name='TerminationSettlement', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('termination_date', models.DateField()),
            ('reason', models.CharField(max_length=20)),
            ('years_of_service', models.DecimalField(decimal_places=2, max_digits=6)),
            ('eosb_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ('leave_balance_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('other_dues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ('total_settlement', models.DecimalField(decimal_places=2, max_digits=12)),
            ('is_paid', models.BooleanField(default=False)),
            ('paid_at', models.DateTimeField(blank=True, null=True)),
            ('notes', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='hr.employee')),
            ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='EmployeeDocument', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('doc_type', models.CharField(max_length=20)),
            ('title', models.CharField(max_length=200)),
            ('file_name', models.CharField(blank=True, max_length=255)),
            ('file_data', models.TextField(blank=True)),
            ('issue_date', models.DateField(blank=True, null=True)),
            ('expiry_date', models.DateField(blank=True, null=True)),
            ('notes', models.TextField(blank=True)),
            ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
        ]),
        migrations.CreateModel(name='SaudizationReport', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('report_date', models.DateField()),
            ('total_employees', models.PositiveIntegerField()),
            ('saudi_employees', models.PositiveIntegerField()),
            ('saudization_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ('nitaqat_band', models.CharField(max_length=20)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ]),
    ]
